### ISSUE TITLE
ANCOVA models and global intercepts

### ISSUE THREAD

**Issue by mjzahn** [QERM514/assistance#36]
For ANCOVA models, do we always drop the global intercept as we saw in lecture/lab? I guess I have a hard time envisioning an example where we would want to keep the global intercept when we have both continuous and categorical variables.

**Comment by mdscheuerell** [comment]
That's a bit tricky, @mjzahn, because the interpretation of the parameter changes when you shift from a means-only model like ANOVA to a means+predictor model like ANCOVA. For example, in this ANCOVA model

y_{i,j} = (beta_0 + alpha_j) + beta_1 * x_{i,j} + e_{i,j}

with alpha_j ~ N(0, sigma_alpha^2) and e_{i,j} ~ N(0, sigma_epsilon^2)

the beta_0 term is a global intercept from which group j's intercept deviates by +/- alpha_j.

**Comment by mjzahn** [comment]
Ahh okay that's helpful! I understand the shift of the intercept by +/- alpha_j from the global intercept, but I'm not sure when it's appropriate to have beta_0 = 0 or not (i.e. when to add the -1 in the lm() function).

When we use the lm() function with both discrete and continuous variables like in our homework for this week, R will correctly identify the categorical variables (e.g. 'aspect') and assign 0 and 1's accordingly. I originally thought we should include the global intercept for this problem, but after reviewing lecture 10 (specifically [slide 54](https://qerm514.github.io/website/lectures/week_04/lec_10_design_matrices.html#54)) I'm confused as to when it's appropriate to drop it or not. Perhaps it's for the cases where it makes sense given the data for the global intercept to be zero (e.g. when ration size is zero, growth will be zero). Do you have any suggestions for how to determine whether we need the global intercept or not?

**Comment by eileenbates** [comment]
I second this question--the parameter estimates all provide an intercept, and I don't think this is an instance where we would expect the predicted variable to be 0 when the predictors are 0, which also may be a signal to leave the intercept in, but I feel as though my understanding here is a bit muddled!

**Comment by mdscheuerell** [comment]
> Ahh okay that's helpful! I understand the shift of the intercept by +/- alpha_j from the global intercept, but I'm not sure when it's appropriate to have beta_0 = 0 or not (i.e. when to add the -1 in the lm() function).

I think there are 2 different issues here, @mjzahn & @eileenbates, but they boil down to understanding the differences/similarities between the models as written on paper vs how they're implemented in a particular software package. 

1) the model shown in [slide 54](https://qerm514.github.io/website/lectures/week_04/lec_10_design_matrices.html#54) has the global intercept dropped for convenience of notation, but it can (and often is) written in terms of an overall mean (eg, "mu") +/- group-specific intercepts (or means in an ANOVA context), with *one* of the _k_ groups having its alpha__j_ = 0. 

2) recall that you can't fit the model as written in [slide 54](https://qerm514.github.io/website/lectures/week_04/lec_10_design_matrices.html#54) with `lm()` because of problems with the design matrix **X**.

So, inclusion/exclusion of any term in a model needs to align with a properly specified design matrix. Once you can determine an appropriate form for **X**, you can always solve for **beta** via the least-squares soln (see [lec 5](https://qerm514.github.io/website/lectures/week_02/lec_05_intro_to_linear_models.html#1)).

**Comment by mjzahn** [comment]
Thanks for clarifying this Mark! I think I'm grasping it. It definitely takes some time getting used to notation standards vs model implementation.
