### ISSUE TITLE
lmer() syntax for RE cheat sheet

### ISSUE THREAD

**Issue by kpjohnson** [QERM514/assistance#40]
Hello QERMpatriots,

I wanted to summarize my notes from an email chain with Mark for anyone who feels lmer() angst:

Let's pretend the subscript for our random effect is `z`

- `(1 | z)` says: give me a random intercept (or a group mean in an ANOVA) for subscript `z`
- `(1 + predictor | z)` says: give me a random intercept and a random slope for my predictor, both for subscript `z`, NOTE: there will be correlation between the intercept and slope
- `(1 + predictor || z)` says: give me a random intercept and a random slope for my predictor with subscript `z` BUT please no correlation between the intercept and slope
- Using a `-1` in the random effects `()`: give me random slopes but no random intercepts

 Thanks, Mark!

**Comment by abigailkeller** [comment]
Thanks for this! I have two questions. Would you ever use bullet 2? Under what circumstances would you want to allow correlation between intercept and slope?
Regarding the last point. Would (0 + predictor  |  z) work instead of -1 to get random slope but no random intercepts?

**Comment by kpjohnson** [comment]
I can't speak for your first question, but when I tried your second question, I got the same results as when I coded -1!

**Comment by hmcmonagle** [comment]
Appreciate you sharing this Kristin!

**Comment by mdscheuerell** [comment]
Here are some answer's to @abigailkeller's Q's.

> Would you ever use bullet 2? Under what circumstances would you want to allow correlation between intercept and slope?

It turns out that in some models, you'd want the intercept and slope to be *inversely* correlated so as to constrain the model given the data. For example, consider fitting a line through a cloud of points. As you increase the intercept, you'd likely need to decrease the slope so as to keep the line within the cloud of points. The case of correlated random effects also arises in some nonlinear models and model with several nested levels of random effects.

Spawner-recruit models are, in fact, one of the examples you might do this, but we don't have enough data to fit those properly. If you try, you'll see that the correlation goes to 1, which means there are some convergence problems and one of the parameters is being estimated as a linear combination of the other. This (usually) indicates an over-specification of the model.

> Would (0 + predictor | z) work instead of -1 to get random slope but no random intercepts?

Yes, I have seen people use `(0 + X | group)` to represent a random effect on only the slope. It also turns out that you can use `(1 | group) + (0 + X | group)` in lieu of `(1 + X || group)` to specify no correlation.

**Comment by abigailkeller** [comment]
Thanks!

**Comment by clohrn** [comment]
Thanks, everyone! This is VERY helpful :)

**Comment by mdscheuerell** [comment]
Cheat sheet from Bates et al.

![Screen Shot 2020-05-15 at 12 44 33 PM](https://user-images.githubusercontent.com/5048528/82090198-fd357580-96a9-11ea-8788-0adb67c77bb7.png)
